### ISSUE TITLE
Wrong file name in yaml template

### ISSUE THREAD

**Issue by jcnovoa** [aws-samples/ac-contactflowapi#2]
https://github.com/aws-samples/ac-contactflowapi/blob/master/template.yaml
Calls for connectflows.html
The file that gets compressed and push to the S3 bucket to deploy to cloudfront is called
contactflowapi.html
The manifest file is also wrong
https://github.com/aws-samples/ac-contactflowapi/blob/master/website-creator/web-site-manifest.json
from
https://github.com/aws-samples/ac-contactflowapi/tree/master/website-creator
Lambda cloudwatch exception:

{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: ENOENT: no such file or directory, open './connectflows.html'",
    "reason": {
        "errorType": "Error",
        "errorMessage": "ENOENT: no such file or directory, open './connectflows.html'",
        "code": "ENOENT",
        "errno": -2,
        "syscall": "open",
        "path": "./connectflows.html",
        "stack": [
            "Error: ENOENT: no such file or directory, open './connectflows.html'",
            "    at Object.openSync (fs.js:462:3)",
            "    at Object.readFileSync (fs.js:364:35)",
            "    at uploadToS3 (/var/task/website-helper.js:77:31)",
            "    at /var/task/website-helper.js:43:17",
            "    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, open './connectflows.html'",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}

**Comment by ramprasadsv** [comment]
Hey JC,
         Thanks for catching the exception, we have corrected this issue, can you please try again.
